config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new", as: "new_session"
  post "/login", to: "sessions#create", as: "create_session"
  get "/logout", to: "sessions#destroy", as: "destroy_session"

  root to: "conversations#index"
  get "/conversations/:id", to: "conversations#show", as: "show_conversation"
  post "/messages", to: "messages#create", as: "create_message"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages

  has_many :conversation_user_joins, dependent: :destroy
  has_many :users, through: :conversation_user_joins, dependent: :destroy
end

app/models/conversation_user_join.rb
class ConversationUserJoin < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  default_scope { order(created_at: :desc) }
  broadcasts_to ->(message) { [message.conversation, "messages"] }, inserts_by: :prepend, partial: "conversations/message"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :conversation_user_joins, dependent: :destroy
  has_many :conversations, through: :conversation_user_joins, dependent: :destroy

  has_many :messages

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_authenticated_user

  def require_authenticated_user
    redirect_to new_session_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index; end

  def show
    @conversation = Conversation.find(params[:id])
    @messages = @conversation.messages.includes(:user)
  end

  def create
    conversation = Conversation.create!(user: current_user)
    message = Message.new(body: params[:message][:body], conversation_id: conversation.id, user_id: current_user.id)
    
    if message.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to show_conversation_path(conversation) }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ActionView::RecordIdentifier

  def create
    @conversation = Conversation.find(params[:message][:conversation_id])
    @message = Message.new(body: params[:message][:body], conversation_id: @conversation.id, user_id: current_user.id)

    if @message.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to show_conversation_path(@conversation.id) }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_authenticated_user

  def new
    return redirect_to root_path if current_user
  end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id

      return redirect_to root_path
    else
      redirect_back fallback_location: new_session_path, alert: "Invalid email or password"
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/_form.html.haml
= form_for(message, url: create_message_path) do |f|
  = f.hidden_field :conversation_id, value: message.conversation.id, id: 'conversation_id'
  .flex
    = f.text_field :body, { class: "w-11/12 rounded-lg border border-gray-500 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none text-gray-700 py-2 px-4 leading-tight", placeholder: "Message..." }
    = f.button type: "submit", class: "custom-submit-button" do
      = raw('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 h-10 ml-4"><path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z" clip-rule="evenodd" /></svg>')

app/views/conversations/_message.html.haml
= content_tag :div, id: dom_id(message) do
  .w-full.my-2
    .flex{ class: "msg-#{message.user.id}"}
      %span.bg-blue-900.text-white.px-4.py-2.rounded-full{class: "content-#{message.user.id}"}= message.body

app/views/conversations/index.html.haml
%h1.text-xl.font-bold="Conversations For #{current_user.name}"
- current_user.conversations.each do |conversation|
  .text-blue-500.underline
    = link_to "#{conversation.users.pluck(:name).join(', ')}", show_conversation_path(conversation)

app/views/conversations/show.html.haml
.w-full.h-16.fixed.top-0
  %h1.pl-32.pr-24.py-4.font-bold.text-lg= @conversation.users.filter { |user| user != current_user }.map(&:name).join(", ")
  %hr.border-2
.mx-4
  .ml-20.mr-24
    = turbo_stream_from @conversation, "messages"
    #messages.h-screen.overflow-y-auto.pt-8.pb-36.flex.flex-col.flex-col-reverse
      - @messages.each do |message|
        = render "conversations/message", message: message
  .w-full.fixed.bottom-16
    .mx-16#message_form
      = render partial: "conversations/form", locals: { conversation: @conversation, message: @conversation.messages.new }
:css
  #{".msg-#{current_user&.id}"} {
  justify-content: flex-end
  }
  #{".content-#{current_user&.id}"} {
  background-color: rgb(37 99 235);
  }

app/views/layouts/application.html.haml
%html
  %head
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = stylesheet_link_tag 'application.tailwind.css', "data-turbo-track": "reload"
  %body.bg-slate-100
    %main.mb-2
      = yield

app/views/messages/create.turbo_stream.haml
= turbo_stream.prepend "messages" do
  = render "conversations/message", message: @message
= turbo_stream.update "message_form", partial: "conversations/form", locals: { message: @conversation.messages.new }